### ISSUE TITLE
Página carpeta (qwikcity)/advanced

### ISSUE THREAD

**Issue by mugan86** [Qwik-Spanish/qwik-i18n-translate-es#15]
Vamos a traducir las páginas correspondientes al [tema advanced (qwikcity)](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced)

- [x] [Menu](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced/menu)
- [x] [Request Handling](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced/request-handling)
- [x] [Routing](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced/routing)
- [x] [Sitemaps](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced/sitemaps)
- [x] [Speculative Module Fetching](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced/speculative-module-fetching)
- [x] [Static Assets](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwikcity)/advanced/static-assets)

**Comment by anartzdev** [comment]
@da8ah yo hago las 3 primeras y tu las 3 últimas si te parece bien, así ya vamos llevándonos todo el contenido por delante

**Comment by da8ah** [comment]
> @da8ah yo hago las 3 primeras y tu las 3 últimas si te parece bien, así ya vamos llevándonos todo el contenido por delante

Hola @anartzdev, me parece perfecto. Tengo otras tareas pendientes y añadiendo estas creo que si las puedo completar en esta semana. En lo personal considero que vamos avanzando bastante bien. 🦾

**Comment by anartzdev** [comment]
Hola @da8ah , tranquilo, ya se que estas con otras tareas, cuando puedas, yo también iré desbloqueando a medida de que pueda. No nos queda tanto, pero nos falta algo más de ayuda. A ver si cuando hagamos esto, vamos perfeccionando la automatización para que no tengamos que estar al 100% metiendo mano, solo comprobando en casos concretos, debería de ser más sencillo.

Muchas gracias por la ayuda!

**Comment by da8ah** [comment]
Me parece espectacular. Yo creo que al paso que vamos si logramos tener una versión en este mes. ¡Qué geniaaal! 🤟
