### ISSUE TITLE
Página carpeta (qwikcity)/qwikcity

### ISSUE THREAD

**Issue by mugan86** [Qwik-Spanish/qwik-i18n-translate-es#23]
En este caso debemos de realizar la traducción del siguiente fichero:
[Qwik City - Qwik City](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/blob/main/(qwikcity)/qwikcity)

**Comment by bezael** [comment]
¿Qué te parece si hago esta tarea? @mugan86

**Comment by anartzdev** [comment]
¡Perfecto, me parece fantástico! Muchas gracias

**Comment by anartzdev** [comment]
@bezael me la asigno, tenemos que ir quitando este trabajo de encima y pensando en lo que es la automatización. Al terminar de traducir todo haré pruebas con el script que he creado junto con DeepL
