### ISSUE TITLE
Páginas carpeta (qwik)/advanced (Avanzado)

### ISSUE THREAD

**Issue by anartzdev** [Qwik-Spanish/qwik-i18n-translate-es#4]
Vamos a traducir las páginas correspondientes al [apartado avanzado del directorio principal (qwik)](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced)

- [x] [containers - Contenedores](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/containers)
- [x] [custom-build-dir -Directorio Personalizado Compilación](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/custom-build-dir)
- [x] [dollar](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/dollar)
- [x] [library - Librería](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/library)
- [x] [optimizer](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/optimizer)
- [x] #29
- [x] [qrl](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/qrl)
- [x] [qwikloader](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/qwikloader)
- [x] [vite](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/vite)

**Comment by manuelsanchez2** [comment]
Veo que en el menu.md del root del repo hay más partes del Advanced, que tienen que ver con qwikcity. Por ahora me centro pues solo en las de qwik, que son las que has puesto en la descripción.

![Image](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/assets/68222396/d1b96084-3539-4086-8939-f9a62fa0b516)

**Comment by da8ah** [comment]
Voy a tomar

- [x] [vite](https://github.com/Qwik-Spanish/qwik-i18n-translate-es/tree/main/(qwik)/advanced/vite) 
 
para hacer la prueba. He realizado un pull request para ver qué tal va: #8

**Comment by mugan86** [comment]
@manuelsanchez2 si, vamos por partes.

@da8ah la idea de primeras es los que vayamos a participar que se vayan creando las tareas y asignándose. Dadme tiempo para preparar todo por favor.

**Comment by da8ah** [comment]
De acuerdo, entonces estaría bien considerar el tablero/pizarra como el punto de entrada y seguimiento para las tareas, ¿no? Creo que para las contribuciones podríamos tomar como referencia las [contribuciones de qwik](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md) mismo. Algo como esto:

Sending a Pull Request
Before submitting a pull request, consider the following guidelines:

-Fork the repository into your own account.
-In your forked repository, create a new branch: git checkout -b my-branch main
Branch names: docs/Nr-qwik-file (docs/07-qwik-faq). Los nombres se han asignado ya por lo que solo se debe actualizar la rama remota.
-Make your changes/fixes.

-Commit your code with a good commit message [using "Commitizen"](https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md#committing-using-commitizen).
-Push your branch to GitHub: git push origin my-branch
-In GitHub, send a pull request to [qwik-i18n-translate-es](https://github.com/Qwik-Spanish/qwik-i18n-translate-es):main.
-If you aren't sure your PR is ready, open it as a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to make it clear to the maintainer.

**Comment by anartzdev** [comment]
El panel ya lo tenemos, es lo primero que se pensó. En el repositorio en la parte de arriba en Projects, tienes la opción de [este panel](https://github.com/orgs/Qwik-Spanish/projects/4/views/1) que es publico.

Ya hay 19 ramas nuevas creadas a partir de esas tareas, prácticamente lo de todo (qwik) y (qwikcity) para ganar yo un poco de tiempo para hacer otras cosas como la guía de contribución y no fallar con mi artículo semanal, que ya poco más de tiempo me dará.

Lo de las instrucciones me iba a inspirar en eso, pero luego iba a darle un toque personal, pero la base si, la que propone el equipo de Qwik
